### ISSUE TITLE
VAU Entitlement-Service PS

### ISSUE THREAD

**Issue by ruiyan-yu** [gematik/epa-deployment#11]
Hi,

the following error appears in the log using vau
`Response: 400 Bad Request
ERROR d.g.e.e.common.LoggingFilter - Error serializing response body to JSON: Java 8 optional type `java.util.Optional<java.lang.String>` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jdk8" to enable handling (through reference chain: io.micronaut.http.hateoas.JsonError["logref"])`

Could this be a dependency error, or is this an issue with my request? curl works just fine
[innerRequest.txt](https://github.com/user-attachments/files/15536662/innerRequest.txt)

best regards

**Comment by IrynaKamenska** [comment]
Hi,

i believe the error is due to the x-useragent is not built correctly. According to the API, it must match the regex: ^[a-zA-Z0-9]{20}/[a-zA-Z0-9\\-\\.]{1,15}$. This means that the xuseragent string must start with exactly 20 alphanumeric characters, followed by a slash, and then 1 to 15 alphanumeric characters, hyphens, or periods. For example: CLIENTID1234567890AB/2.1.12-45. The error message is actually a violation of the validation constraint and is unfortunately misleading. We need to improve this.
best regards

**Comment by ruiyan-yu** [comment]
Hi,

thanks, sry about the x-useragent.
i changed the x-useragent to CLIENTID1234567890AB/2.1.12-45, but the some error still appears in the log
`2024-06-03 18:57:50 16:57:50.500 [default-nioEventLoopGroup-1-13] INFO  d.g.e.e.common.LoggingFilter - Response: 400 Bad Request
2024-06-03 18:57:50 16:57:50.500 [default-nioEventLoopGroup-1-13] ERROR d.g.e.e.common.LoggingFilter - Error serializing response body to JSON: Java 8 optional type `java.util.Optional<java.lang.String>` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jdk8" to enable handling (through reference chain: io.micronaut.http.hateoas.JsonError["logref"])`
[innerRequest_proper_useragent.txt](https://github.com/user-attachments/files/15537222/innerRequest_proper_useragent.txt)


best regards

**Comment by IrynaKamenska** [comment]
Hi,

i tried your request locally and it worked. Strange. I have no solution right now.
I'll think about it again tomorrow. 
best regards,

[setEntitlementsPs.txt](https://github.com/user-attachments/files/15537387/setEntitlementsPs.txt)

**Comment by ruiyan-yu** [comment]
Hi, 

the "Content-Length" was missing in the innerRequest. oops😥 
curl sends data in the same way that a browser does, the browser calculates the content length automatically. 

best regards and thanks for the support
