### ISSUE TITLE
cURL Malformed Request InformationService

### ISSUE THREAD

**Issue by ruiyan-yu** [gematik/epa-deployment#19]
Hi,

I'm encountering a "malformedRequest" error when accessing the InformationService. Is this a known issue?

best regards

consent decisions
```
*   Trying 127.0.0.1:8082...
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET /information/api/v1/ehr/Z1234567891/consentdecisions HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 400
< Content-Type: application/json;charset=utf-8
< Content-Length: 33
< Date: Sun, 07 Jul 2024 20:12:16 GMT
< Connection: close
<
* Closing connection 0
{"errorCode": "malformedRequest"}
```

record status
```
*   Trying 127.0.0.1:8082...
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET /information/api/v1/ehr/Z1234567891 HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 400
< Content-Type: application/json;charset=utf-8
< Content-Length: 33
< Date: Sun, 07 Jul 2024 20:17:36 GMT
< Connection: close
<
* Closing connection 0
{"errorCode": "malformedRequest"}
```

**Comment by fnoGematik** [comment]
Hi @ruiyan-yu,

the "malformedRequest" is a specific error type that is defined in the [OpenAPI YAML](https://github.com/gematik/ePA-Basic/blob/ePA-3.0.2/src/openapi/I_Information_Service.yaml#L138) description for the information service backend.

Incidentally, the parameter "insurantId" has [changed](https://github.com/gematik/ePA-Basic/blob/ePA-3.0.2/src/openapi/I_Information_Service.yaml#L224) from a path parameter to a header parameter "x-insurantid". You must therefore change your request message accordingly.

Best regards,
