### ISSUE TITLE
How to incorporate use of proxy server in ps-testsuite.yml

### ISSUE THREAD

**Issue by ThoWenk** [gematik/epa-deployment#22]
When I deploy the container for ps-testsuite I am not able to download plugin for Maven. I tried to incorporate our proxy as -MAV-OPTS as well under environment. Nothing was working. Due to that the container excited immediately.

I don't have that much experience in docker and reading documentation and searching gave me some ideas. But now I am not sure, what is the correct way. Maybe someone can help me?

---Snip
name: dc-testsuite
services:
  ps-testsuite:
    image: gematik1/ps-testsuite:1.0.7
    container_name: ps-testsuite
    restart: 'no'
    environment:
      - MAVEN_OPTS=-Dcucumber.filter.tags=${PS_TESTSUITE_TESTS}  -Dhttp.proxyHost=192.168.106.1 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=192.168.106.1 -Dhttps.proxyPort=8080         
      - HTTP_PROXY=192.168.106.1:8080
      - HTTPS_PROXY=192.168.106.1:8080
      - NO_PROXY=localhost, 127.0.0.1
---Snap

[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< de.gematik:ps-testsuite >-----------------------
[INFO] Building ps-testsuite 1.0.7-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/jacoco/jacoco-maven-plugin/0.8.12/jacoco-maven-plugin-0.8.12.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  40.334 s
[INFO] Finished at: 2024-07-19T14:11:48Z
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.jacoco:jacoco-maven-plugin:0.8.12 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.jacoco:jacoco-maven-plugin:jar:0.8.12: The following artifacts could not be resolved: org.jacoco:jacoco-maven-plugin:pom:0.8.12 (absent): Could not transfer artifact org.jacoco:jacoco-maven-plugin:pom:0.8.12 from/to central (https://repo.maven.apache.org/maven2): Network unreachable -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

Thx a ton and best regards,
Thomas

**Comment by IrynaKamenska** [comment]
Hi, 

this sounds like a similar problem to the one discussed here: https://github.com/gematik/epa-deployment/issues/17 Please take a look at it. I hope it can help.

Best regards,
Iryna

**Comment by fnoGematik** [comment]
Hi @ThoWenk,

we released another updated version of our epa-deployment with the option to define maven proxy settings for ps-testsuite. Please have a closer look to the [ReadMe Part](https://github.com/gematik/epa-deployment/blob/main/README.md#proxy-configuration-for-ps-testsuite).

Best regards,
