### ISSUE TITLE
Documentation on medication-render-service inconsistent/incorrect

### ISSUE THREAD

**Issue by CEiderEVIDENT** [gematik/epa-deployment#27]
Actual documentation says

.....
To retrieve the eML as FHIR Resource execute the following curl command:

curl --location http://localhost:8084/fhir/Medication?status=active
........

1. Inconsistent, as in all other examples the host  of the call is abstracted to "<docker-host>" and not  "localhost"
2. Incorrect, as examples  results in an html-page not in an fhir/xml document. Either accept-header has to be set or a request-parameter has to be used like _format=xml

**Comment by sonerd** [comment]
Hi @CEiderEVIDENT ,

1. We will fix the readme as you have mentioned.

2. We cannot reconstruct the issue as mentioned. If we execute the CURL we get the related medications in JSON format. Could it be, that you have forgotten to import the samples into the medication service? As described in the readme, after starting the services you have to import the medication samples into the service.

Regards.

**Comment by CEiderEVIDENT** [comment]
@sonerd 

(2) is even not reproducable anymore on my system. Sub-Issue can be ignored
Tia Carsten

**Comment by sonerd** [comment]
@CEiderEVIDENT we just released a new version with the fix of (1)
