### ISSUE TITLE
Unauthenticated request

### ISSUE THREAD

**Issue by ruiyan-yu** [gematik/epa-deployment#3]
Hi,

Müssen wir uns zusätzlich bei der Gematik registrieren?

`Error response from daemon: Head "https://eu.gcr.io/v2/gematik-all-infra-prod/epa/vau-proxy-server/manifests/latest": denied: Unauthenticated request. Unauthenticated requests do not have permission "artifactregistry.repositories.downloadArtifacts" on resource "projects/gematik-all-infra-prod/locations/europe/repositories/eu.gcr.io" (or it may not exist)`

**Comment by sonerd** [comment]
Hi @ruiyan-yu, der letzte Stand in github ist noch "Work in progress". 
Bitte noch bis zum 01.05 warten. Das ist der Termin, wo wir den neuesten und offiziellen Stand veröffentlichen werden. Die notwendigen Images werden dann von docker-hub kommen.
