### ISSUE TITLE
PS-Testsuite can not decode VAU traffic, leading to false negative testcases (e.g. VAU testcase)

### ISSUE THREAD

**Issue by cgeesink** [gematik/epa-deployment#31]
PS-Testsuite use old tigerProxy Dependency, but docker compose use new TigerProxy Version. Because of the old Dependency, the PS-Testsuite must use the old configuration parameter for Epa3Vau decoding.

Without the old parameter the Testsuite cant decode the inner VAU traffic. Leading to failed testcases because of failed validation of inner objects in the (undecoded) VAU traffic.

PR with Fix https://github.com/gematik/epa-deployment/pull/30

**Comment by fnoGematik** [comment]
Hi @cgeesink ,

as you may notice, we have transferred the PR to the main branch. Nonetheless, the migration to a current Tiger lib in ps-testsuite will happen soon.
