### ISSUE TITLE
Tiger-proxy SSL issue 

### ISSUE THREAD

**Issue by jisspala** [gematik/epa-deployment#34]
**This is a follow-up ticket to** https://github.com/gematik/epa-deployment/issues/28.

First of all, thank you for your support and answers, which have been very helpful.

We have tried using the latest version of the repository and added the root CA to the local trust store, both in the browser and the system. However, the HTTPS protocol is still not working properly.

What is the expected result when accessing https://localhost/ in the browser? Below is a screenshot of the result we are encountering.
![Screenshot from 2024-09-20 09-55-54](https://github.com/user-attachments/assets/501c835b-0df6-478d-8879-bf93ce9b88a2)

That said, **we are able to use the EPA APIs** in our Node.js app by disabling the **SSL check.**

One more thing I'd like to mention, which is not directly related to this issue...

when we are calling the epa api https://localhost/epa/authz/v1/send_authorization_request_sc . 
we are getting the URL in header as  https://idp-ref.app.ti-dienste.de?redirect_uri=https%3A%2F%2Ftest-ps.gematik.de%2FePA&client_id=client_id&state=state&nonce=nonce&code_challenge=code_challenge&code_challenge_method=S256&scope=gem-auth+openid&response_type=code which is not working, 

But if change this URL as
https://idp-ref.app.ti-dienste.de/auth?redirect_uri=https%3A%2F%2Ftest-ps.gematik.de%2FePA&client_id=client_id&state=state&nonce=nonce&code_challenge=code_challenge&code_challenge_method=S256&scope=gem-auth+openid&response_type=code

Then it works . We are not sure which one we need to use.

Thanks in Advance :)

**Comment by Arkinator** [comment]
Is your vau-proxy-server up and running? 
From this configuration https://github.com/gematik/epa-deployment/blob/main/tiger-proxy/application.yaml you can see that requests to "/" would simply be forwarded to that server. The non-http closing of a connection indicates an out-of-bounds error. I suspect that the error will be logged to the console, and given that configuration the most likely candidate would be an unreachable remote host.

**Comment by fnoGematik** [comment]
Hey @jisspala ,

You were absolutely right. The path “/auth” was missing in the response of our authorization mock service. This was fixed with version 1.0.14, which was released a while ago.

Is this ticket generally still open or can it already be closed?

Best regards,
