### ISSUE TITLE
PS-Testsuite Test Failed

### ISSUE THREAD

**Issue by ruiyan-yu** [gematik/epa-deployment#8]
RbelLog indicates a successful handshake, but RebelMessageValidator can't find a message with the matching cid.
[RbelMessageValidator_AssersionError.zip](https://github.com/gematik/epa-deployment/files/15366885/RbelMessageValidator_AssersionError.zip)

**Comment by fnoGematik** [comment]
Hi @ruiyan-yu,

the issues is tracked with an internal ticket. We'll have a closer look to this issue report. 
*.tgr file is attached - perfect 👍.

I'll give you an anwser asop.

**Comment by fnoGematik** [comment]
Hi @ruiyan-yu,

I didn't get any internal feedback yet, but could you provide us the log of ps-testsuite container?
Is this issue always reproducible on your side or does it occurs "sometimes"?

Thanks for your support & best regards,

**Comment by ruiyan-yu** [comment]
Hi @fnoGematik,

I've figured out how to get the workflow-ui working. 
It turns out that you need to pause the handshake after receiving M2 and then resume it when the workflow-ui is waiting for M3.

If you complete the entire handshake at once, as I expected, the M3 request with the $(vauCid) is filtered out at an early stage, the same stage as M1. As a result, the workflow-ui can't locate M3 later on.
[ps-testsuite.zip](https://github.com/gematik/epa-deployment/files/15422058/ps-testsuite.zip)

Best Regards

**Comment by fnoGematik** [comment]
Thank you @ruiyan-yu for your detailed feedback. That helps a lot :-).
An update with a correction is on the way.

There is a half second pause in my [example](https://github.com/gematik/epa-deployment/blob/main/doc/html/VauHandshakeAndUserSession.mhtml).
That's a bit strange to me, but my colleagues will figured it out :-P.

Stay tuned and best regards,

**Comment by fnoGematik** [comment]
Hey @ruiyan-yu,

we released a new version of this repo with an updated version of the test framework (tiger). 
Could you please check whether the issue has been solved?

Kind regards and sorry for the delay,

**Comment by ruiyan-yu** [comment]
Hi @fnoGematik ,

thank you, It works :)
[trafficLog-240610.zip](https://github.com/user-attachments/files/15757489/trafficLog-240610.zip)

best regards
