### ISSUE TITLE
VAU Response from medication-render-service 

### ISSUE THREAD

**Issue by ruiyan-yu** [gematik/epa-deployment#9]
Hi,

I can retrieve the PDF from the medication-render-service using the curl command without any issues.

However, When I send the request via VAU, I receive a response which can be decrypted (HTTP 200 inner), but the content-length does not match the actual payload size. The payload is larger. As a result, the PDF is corrupted and cannot be opened because it's incomplete. Even after manually extracting the bytes with the actual length and writing them to a file, the PDF still can't be opened. 

It seems to be an encoding problem. Is anyone else experiencing this issue?

[diff_hex_header.zip](https://github.com/gematik/epa-deployment/files/15472254/diff_hex_header.zip)
[pdfs.zip](https://github.com/gematik/epa-deployment/files/15472289/pdfs.zip)

**Comment by fnoGematik** [comment]
Hey @ruiyan-yu,

I'll try to reproduce this issue locally. 

Anyway. Could you please try to get the PDF from medication-render-service without using VAU De-/encryption.
To do so, send the request to http://<docker-host>:8085/epa/medication/render/v1/eml/pdf.

Best regards,

**Comment by fnoGematik** [comment]
Hey @ruiyan-yu,

yesterday I found an issue with an unnecessary type conversion in vau-proxy-server and I was able to reproduce the behavior you described ( Header Content-Lenght was different to the payload size and the payload was not the same as the origin.
I already have a fix. I hope we can updated this repository a.s.a.p..

Best regards,

**Comment by fnoGematik** [comment]
Hey @ruiyan-yu,

we have just released a new version of the vau-proxy-server which contains the fix. If it is possible for you, you are welcome to check whether the fix also solves your problem. All you have to do is update the version of the vau-proxy-server to 1.0.5, which is already published on DockerHub, in the dc-mocks.yaml file. 
Your feedback is welcome.

Best regards,

Best regards,

**Comment by sonerd** [comment]
Hey @ruiyan-yu,

we have just released a new version of this deployment project. This includes the fix for your problem. Please give it a try.

Thanks.

**Comment by ruiyan-yu** [comment]
Hi,

It's working perfectly! Thank you for the hotfix and for setting up the new entitlement service. :)

Best regards
